.build.yml, include/pipewire_screencast.h, include/screencast_common.h, meson.build, src/core/main.c, src/screencast/pipewire_screencast.c, src/screencast/screencast_common.c
=> Add pipewire 0.3 support. Workaround pipewire bugs.

src/core/main.c, src/core/session.c, src/screencast/pipewire_screencast.c, src/screencast/screencast.c, src/screencast/wlr_screencast.c
=> Check refcount again before attaching new session

include/screencast_common.h, include/xdpw.h, src/core/main.c, src/screencast/pipewire_screencast.c, src/screencast/screencast.c, src/screencast/screencast_common.c
Tested with Chromium.
Closes: https://github.com/emersion/xdg-desktop-portal-wlr/issues/23
=> Advertise format with alpha channel stripped

src/screencast/wlr_screencast.c
Fixing the if statement to an 80 character linewidth
=> Fix linewidth in wlr_screencast.c

README.md
The package has been moved from the AUR to the official `community` repo.
=> Link official Arch Linux package in readme

src/screencast/pipewire_screencast.c
Make sure that in SPA_POD_CHOICE_ENUM_Id(n_vals, ...) we always pass
exactly n_vals arguments.
Fix #102
Tested on wlroots 0.12 (format with alpha) and wlroots master (format without alpha)
=> pipewire: Fix building EnumFormat spa object

.builds/alpine.yml, .builds/archlinux.yml, .builds/freebsd.yml
- Add `scdoc` dependency
- Set `-Dauto_features=enabled`
- Manually specify `-Dsd-bus-provider=[...]` for each platform
- Set `-Dsystemd=disabled` for alpine and freebsd
=> Update CI config to build man pages

.builds/freebsd.yml, meson.build, protocols/meson.build
=> build: improve iniparser dependency lookup

src/core/main.c
These can be specified in the configuration file now.
=> Remove -o and -f options

src/screenshot/screenshot.c
This adds reading the screenshot message options and if the `interactive` option is set, prompts the user to select a screen region with slurp before taking the screenshot.
Would close #45 
I am still very unfamiliar with C, so any comments or corrections are appreciated.
Also I wasn't quite sure about the approach, since for screencasting the chooser command is configurable. In the case of using slurp + grim their coordinate formats are compatible, so no parsing needs to be done, but I'm not sure if potential other chooser applications would be expected to output their coordinates in the same format or if the result needs to be parsed.
=> Screenshot: Implement `interactive` option

include/screenshot.h, src/screenshot/screenshot.c
I couldn't find any application to test this method, so i just used the usual python script and modified it a bit: https://gist.github.com/junglerobba/e3985bc66a025aed6beb5edfee1ed900
Not sure if the whole ppm parsing is really necessary, but I felt it was safer to do so.
closes #129
=> Screenshot: Implement PickColor method

README.md
=> readme: misc. improvements

src/core/config.c, xdg-desktop-portal-wlr.5.scd
Also fixes memory leak in get_config_path
=> Parse XDG_CURENT_DESKTOP as list

src/screencast/pipewire_screencast.c
This MR creates a seperate function to build pipewire formats.
=> pipewire cleanup buildformat

src/core/config.c
This does not seem to be an error and cost me some time to realize, so I fixed it for everyone else.
=> chore(logging): change config file error to info

include/pipewire_screencast.h, include/screencast_common.h, src/screencast/pipewire_screencast.c, src/screencast/screencast.c, src/screencast/screencast_common.c, src/screencast/wlr_screencast.c
This MR aims to implement screensharing with dmabufs with the new workflow using pipewire buffers.
NOTE:
This is work in progress and will change frequently.
Depends: #141 
Includes: #159 
Supersedes #48 
Resolves: #9
=> dmabuf support next generation

src/screencast/screencast.c
When a screencast is started we do a roundtrip on get the offered
formats from wlr_screencopy. This roundtrip can fail [1]. In this case
the formats won't be initialized and we will just error out of the
screencast session.
[1] https://github.com/emersion/xdg-desktop-portal-wlr/issues/214
=> screencast: check if a valid format was received from wlr_screencopy

include/screenshot_common.h, include/xdpw.h, src/core/main.c, src/screenshot/screenshot.c
Announces implemented API version via dbus.
Closes: #230
=> Screenshot version

include/screencast_common.h, meson.build, src/screencast/pipewire_screencast.c, src/screencast/wlr_screencast.c
PipeWire MR: https://gitlab.freedesktop.org/pipewire/pipewire/-/merge_requests/1423
Example client: https://github.com/obsproject/obs-studio/pull/7762
=> screencast: Send buffer transform information via PipeWire

include/screenshot_common.h
Since we don't support the permission store yet, we should only announce support for version 1
=> screenshot: announce version 1

src/screencast/pipewire_screencast.c
Modern GPUs support many modifiers which increases the size required for the param_buffer. Instead of randomly bumping the hardcoded value we can use spa_pod_dynamic_builder, which increases the buffer automatically.
Superseedes: #258
=> screencast: Use spa_pod_dynamic_builder

include/screencast_common.h, src/screencast/pipewire_screencast.c, src/screencast/screencast_common.c, src/screencast/wlr_screencast.c
I'd like to have a client using this, but it's probably a hen/egg problem. Tested this with a OBS patched to only draw the damaged part and that worked.
=> screencast: send damage via PipeWire

src/screencast/pipewire_screencast.c
xdg-desktop-portal-wlr previously only set the buffer type of the first plane of the buffer. This, among possibly other issues, causes the file descriptor of DMA-BUF buffers to get lost somewhere between the pipewire daemon and the consuming application (e.g. obs).
The client libpipewire will see a buffer with a type of -1, and will proceed to drop the file descriptor, leaving the user with an invalid DMA-BUF if the format has more than one plane. This fixes that issue.
I initially encountered this issue trying to add xdg-desktop-portal support to [wl-mirror](https://github.com/Ferdi265/wl-mirror), but the same issue also happens with [obs-studio](https://github.com/obsproject/obs-studio).
With obs, this manifests as obs first negotiating a tiled format with 2 planes, failing to import …
=> Screencast: fix buffer type only being set on first plane

src/screencast/pipewire_screencast.c
If the pipewire daemon restarted while xdpw was running then our pipewire connection would drop and attempting to start a screencast wouldn't work until user manually restarted xdpw.
This commit adds a listener for fatal core connection errors from pipewire.  In the handler it cleans up the connection and marks it as dead.  Then, when the user attempts to start a screencast, we reconnect the pipewire core if needed.
To reproduce the problem:
- Start off with pipewire, xdg-desktop-portal, and xdg-desktop-portal-wlr running as normal in a working state
- `systemctl --user restart pipewire`
- Go to https://mozilla.github.io/webrtc-landing/gum_test.html in a recent release of Firefox and click "Screen capture"
- The screen capture does not start and xdg-desktop-portal-wlr hangs, consuming a …
=> Handle pipewire restarts

src/screencast/screencast_common.c
=> screencast: add support for format BGR

meson.build
We can just pass all of the lbraries to try as an array.
=> build: simplify sd-bus-provider=auto

contrib/wlroots-portals.conf
See also: https://github.com/flatpak/xdg-desktop-portal/pull/1277
=> contrib: fix typo in the portals config example

src/screencast/screencast_common.c
No need to list all DRM devices, we already have a drmDevice pointer passed in.
=> screencast: simplify xdpw_gbm_device_create()

src/screenshot/screenshot.c
As #307 but for the general screenshot functionality.
=> screenshot: clean up xdpw request #307 

include/ext_image_copy.h, include/screencast_common.h, meson.build, protocols/meson.build, src/core/session.c, src/screencast/ext_image_copy.c, src/screencast/pipewire_screencast.c, src/screencast/screencast.c, src/screencast/screencast_common.c, src/screencast/wlr_screencast.c, src/screencast/wlr_screencopy.c
Implement ext_image_copy_capture_v1.
Notes:
- I don't have a test for the wl_shm bits - any suggestions?
- Support for capturing 10-bit output with 8-bit clients requires https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/5019
=> ext_image_copy_capture_v1: Initial implementation
