emersion/xdg-desktop-portal-wlr

- include/xdpw.h
- screenshot.c
Combine multiple `sd_bus_message_append` calls.
Reduces repetition and error handling overhead, makes it easier to see at a glance what is being done.
> Use sd_bus_message_append shorthand for screenshot

- README.md
I haven't managed to get `portal-test` to work yet, so have also included links to the python snippets.
> Add tooling to README mentioning portal-test and python snippets

- meson.build
libdrm was missing in `meson.build` file, so configuration did not detect when it was absent from the system.
> add missing libdrm to meson.build

- contrib/systemd/xdg-desktop-portal-wlr.service.in
- meson.build
- meson_options.txt
- org.freedesktop.impl.portal.desktop.wlr.service.in
Also change install location to libexec as it seems to be used for all other xdg-desktop-portal implementations.
> Add D-Bus and systemd service files

- .build.yml
- include/logger.h
- include/pipewire_screencast.h
- include/screencast.h
- include/screencast_common.h
- include/wlr_screencast.h
- include/xdpw.h
- meson.build
- src/core/logger.c
- src/core/main.c
- src/core/request.c
- src/core/session.c
- src/screencast/pipewire_screencast.c
- src/screencast/screencast.c
- src/screencast/screencast_common.c
- src/screencast/wlr_screencast.c
- src/screenshot/screenshot.c
Fixes #13.
This is designed to take pairs of output id and cursor mode and create a single pipewire stream for each unique combo. Until output selection can be controlled at screencast initialization, this doesn't serve much of a purpose, but it is designed with that capability in mind.
~~At the moment, this gets all the way to a pipewire stream PAUSED state and continues processing wlroots frames like it is supposed to, but the stream is not able to activate. I need to investigate changes made to the pipewire portions of the code to see if I created a regression.~~
Edit: The pipewire issues are fixed.
@emersion, in order to give all of these event driven functions an understanding of which session they belong to, I've started to pass around "cast" session objects instead of the …
> Screencast session support

- meson.build
- src/screencast/screencast.c
- src/screencast/wlr_screencast.c
This should fix our issues with musl (#28), but pipewire spa code is still misbehaving.
> Fix musl issue with time.h

- src/core/main.c
The error handling at the `error:` label tears down the whole state. Thus, the state needs to be fully initialized in order for the tear down to succeed. Currently, if e.g. `sd_bus_open_user()` fails, a `segfault` is triggered by the tear down. This commit adds individual tear down code that only touches
stuff that until that point was successfully initialized.
> core/main.c: Fix error handling

- src/core/main.c
- No need to create a linker symbol for `xdpw_usage()`
- Using `EXIT_SUCCESS` and `EXIT_FAILURE` over magic numbers is more readable
> core/main: Minor cleanup

- src/core/main.c
- Add a missing space in the usage string
- Drop short option "p", which is unused
> core/main: Clean up option handling

- contrib/systemd/xdg-desktop-portal-wlr.service.in
I'm learning more about systemd 🙂 
`PartOf=` will ensure that when graphical session ends, this service will be gracefully shutdown. Otherwise display just disappears, and I think the process will crash.
`After=` is only needed to give systemd a hint about order of starting services, I don't think it's strictly necessary for a DBUS-activated service like this one or mako, I guess people add it mostly for semantic reasons.
`[Install]` is not really needed for a DBUS-activated service, because it will start even if you don't `systemctl enable` it.
However if you want I can add it (like in mako), and the effect will be that if a user explicitly `systemctl enable`s this service, it will be launched not on DBUS, but immediately after graphical session starts.
> systemd: ensure service is stopped on exit of graphical session

- src/screencast/wlr_screencast.c
This draft tries to minimize creation and destruction of the cast->simple_frame.buffer and cast->simple_frame.data.
> screencast/wlr_screencast Reuse wl_buffer if possible

- src/screencast/wlr_screencast.c
This reverts commit cc59abb1247c496ed80611c5ed30c9f662eecb0f.
Fixes emersion/xdg-desktop-portal-wlr#50
> Revert "Remove unnecessary check from wlr_screencast.c"

- meson.build
- src/screencast/pipewire_screencast.c
Pipewire has a bitmap (dataType buffer parameter) to compare the available buffer types since 0.3.2.
> Add pipewire buffers_dataType parameter in pipwire_screencast.c

- include/wlr_screencast.h
- protocols/wlr-screencopy-unstable-v1.xml
- src/screencast/wlr_screencast.c
This PR updates the wlr-screencopy-unstable-v1 to version 3 with only implementing an shm buffer. It also provides an fallback to version 2, if the compositor only supports that. It also lists all available protocols with the used version at startup, when in loglevel debug.
> Update to wlr-screencopy-unstable-v1 version 3

- wlr.portal
Quick and dirty change. I intend to add some basic setup to the readme as well, if nobody else is doing that. Mainly just a hint to use the systemctl or dbus to systemd environment setup in autostart, or else the auto loaded portal won't actually work.
> Add Wayfire to portal UseIn list, as it is also supported

- src/screencast/pipewire_screencast.c
Don't announce a SPA_PARAM_BUFFERS_dataType. This is reserved for consumer
> Remove SPA_PARAM_BUFFERS_dataType

- src/screencast/screencast.c
see https://github.com/emersion/xdg-desktop-portal-wlr/blob/master/src/core/main.c#L100, or https://github.com/flatpak/xdg-desktop-portal-gtk/blob/master/src/screencast.c#L542
> Fix cursor_mode checks in screencast.c

- .builds/freebsd.yml
- include/pipewire_screencast.h
- include/xdpw.h
- meson.build
- meson_options.txt
- src/screencast/pipewire_screencast.c
Depends on #77
@myfreeweb, can you test runtime and identify what's missing? Already in ports for easy testing.
> Unbreak build on FreeBSD

- src/screencast/pipewire_screencast.c
- src/screencast/wlr_screencast.c
When a frame is skipped, we weren't destroying the wlr frame. Since
this function kicks off the next frame capture, the stream was getting
stuck.
Disclaimer: I can't reproduce, please test.
Closes: https://github.com/emersion/xdg-desktop-portal-wlr/issues/81
> Fix freeze on skipped frame

- src/core/main.c
This allows replacing a running xdpw instance. xdg-desktop-portal
itself has this feature.
This is useful when developing, to stop the currently running
system instance.
> Add --replace flag

- .builds/alpine.yml
- .builds/archlinux.yml
- .builds/freebsd.yml
- contrib/config.sample
- include/config.h
- include/logger.h
- include/screencast_common.h
- include/xdpw.h
- meson.build
- src/core/config.c
- src/core/logger.c
- src/core/main.c
- src/screencast/screencast.c
Resolves #60 
Note: while this is not merged and man pages are not ready, the locations for a config file are in order:
* $XDG_CONFIG_HOME/xdg-desktop-portal-wlr/$XDG_CURRENT_DESKTOP
* $XDG_CONFIG_HOME/xdg-desktop-portal-wlr/config
* $HOME/.config/xdg-desktop-portal-wlr/$XDG_CURRENT_DESKTOP
* $HOME/.config/xdg-desktop-portal-wlr/config
* /etc/xdg/xdg-desktop-portal-wlr/$XDG_CURRENT_DESKTOP
* /etc/xdg/xdg-desktop-portal-wlr/config
* /etc/xdg-desktop-portal-wlr/$XDG_CURRENT_DESKTOP
* /etc/xdg-desktop-portal-wlr/config
The system wide config can be in another place, if SYSCONFDIR differs from /etc
> Add support for config file

- src/core/config.c
configfile is a `char *`. %s needs a `char *`, so we shouldn't
dereference the pointer here.
Closes: https://github.com/emersion/xdg-desktop-portal-wlr/issues/91
> Fix segfault in config_parse_file

- CONTRIBUTING.md
The original snippet was deleted from the GNOME GitLab instance. I had an old copy lying around and reuploaded it as a gist for safe keeping. Link is updated to point at this gist.
> Fix link to trigger-screen-shot.py

- .builds/freebsd.yml
- contrib/config.sample
- include/config.h
- include/fps_limit.h
- include/screencast_common.h
- include/timespec_util.h
- include/xdpw.h
- meson.build
- src/core/config.c
- src/core/main.c
- src/core/timer.c
- src/core/timespec_util.c
- src/screencast/fps_limit.c
- src/screencast/screencast.c
- src/screencast/wlr_screencast.c
Addresses #66 by introducing an optional command-line argument to limit the number of frames captured per second, as the mouse lag issue becomes less noticeable if the frame rate is smaller. The argument represents the targeted frames-per-second value (e.g. pass `-f 10` for 10 FPS).
The implementation took inspiration from https://github.com/any1/wayvnc, but no code was copied other than the file `include/time-util.h`.
The actual FPS value can be lower than the targeted one because xdg-desktop-portal-wlr uses the `zwlr_screencopy_frame_v1_copy_with_damage` function (emphasis on `with_damage`), which waits until the screen changes.
The implementation differs from that of wayvnc that it does not try to "smooth" the capture rate over time, and it always uses the capture time of the last …
> Control how many frames are captured per second

- src/core/config.c
Drop some config paths from our lookups. See each commit for an explanation.
cc @columbarius
> Simplify config paths

- include/config.h
- src/core/config.c
- src/screencast/screencast.c
- xdg-desktop-portal-wlr.5.scd
I personally find this very useful to disable notifications during a screencast so I thought I'd just put it out there.
It's the first time I touch this codebase so I'm not sure whether I put everything in the right place.
> Add exec_before and exec_after

- contrib/config.sample
- include/config.h
- include/screencast_common.h
- include/wlr_screencast.h
- src/core/config.c
- src/core/logger.c
- src/core/main.c
- src/screencast/screencast.c
- src/screencast/screencast_common.c
- src/screencast/wlr_screencast.c
- xdg-desktop-portal-wlr.5.scd
This provides the posibility to choose the screencast display via a graphical interface provided either by slurp, wofi or dmenu. If a display is given via, the commandline parameter, it is prioritised, in case all selectors fail, it will fall back to the current default. For slurp to work properly https://github.com/emersion/slurp/pull/64 is required.
Note: while this is not merged and man pages are not ready, the locations for a config file are in order:
$XDG_CONFIG_HOME/xdg-desktop-portal-wlr/$XDG_CURRENT_DESKTOP
$XDG_CONFIG_HOME/xdg-desktop-portal-wlr/config
$HOME/.config/xdg-desktop-portal-wlr/$XDG_CURRENT_DESKTOP
$HOME/.config/xdg-desktop-portal-wlr/config
/etc/xdg/xdg-desktop-portal-wlr/$XDG_CURRENT_DESKTOP
/etc/xdg/xdg-desktop-portal-wlr/config …
> Add graphical display chooser

- src/core/config.c
```
../src/core/config.c: In function ‘finish_config’:
../src/core/config.c:26:9: error: ‘free’ called on pointer ‘config_7(D)’ with nonzero offset 16 [-Werror=free-nonheap-object]
26 |         free(&config->screencast_conf.exec_before);
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/core/config.c:27:9: error: ‘free’ called on pointer ‘config_7(D)’ with nonzero offset 24 [-Werror=free-nonheap-object]
27 |         free(&config->screencast_conf.exec_after);
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/core/config.c:28:9: error: ‘free’ called on pointer ‘config_7(D)’ with nonzero offset 32 [-Werror=free-nonheap-object]
28 |         free(&config->screencast_conf.chooser_cmd);
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as …
```
> Fix gcc warnings on invalid `free` call

- src/screencast/wlr_screencast.c
This MR aims to fix the corrupted output list after a monitor hotplug.
Related to #76
> screencast: fix monitor hotplug

- src/screencast/wlr_screencast.c
wl_display_dispatch is unnecessary and can cause hangs, if no new requests are queued
> wlr_screencast: remove wl_display_dispatch

- src/screencast/wlr_screencast.c
Running `xdpw` with no configs (`default` chooser_type) didn't work for me (white window in gum_test on firefox). I didn't have `slurp` nor `wofi` installed, but I had `bemenu`.
Before this patch:
```
2021-04-18 19:39:13.817617637 2021/04/18 19:39:13 [INFO] - wlroots: capturable output: Unknown model: 0x05DF: id: 39 name: eDP-1
2021-04-18 19:39:13.817628300 2021/04/18 19:39:13 [INFO] - wlroots: capturable output: Samsung Electric Company model: S22F350: id: 40 name: HDMI-A-2
2021-04-18 19:39:13.817637339 2021/04/18 19:39:13 [DEBUG] - wlroots: output chooser called
2021-04-18 19:39:13.817647155 2021/04/18 19:39:13 [DEBUG] - wlroots: output chooser called
2021-04-18 19:39:13.817687751 2021/04/18 19:39:13 [TRACE] - exec chooser called: cmd slurp -f %o -o, pipe chooser_in (14,15), pipe …
```
> wlr_screencast: fix return value on cmd failure

- src/screencast/wlr_screencast.c
This reverts commit 94f1f5d0a8e9387057b643111d9909f25395fa10.
After fixing the #109 we probably can remove that check. Will test it the next days
> Revert "screencast: workaround corrupted output_list"

- wlr.portal
XDG_CURRENT_DESKTOP can contain a list [1]. Allow users to
set a list such as XDG_CURRENT_DESKTOP=asdf:wlroots. That way, users
can use xdpw in their non-Sway compositor without specifying
XDG_CURRENT_DESKTOP=sway and without having to edit the portal
definition.
[1]: https://github.com/flatpak/xdg-desktop-portal/blob/9a2582d035a397efbb330c53f893d5649c1fd749/src/portal-impl.c#L189
> Add wlroots to portal manifest UseIn list

- contrib/config.sample
- src/screencast/wlr_screencast.c
- xdg-desktop-portal-wlr.5.scd
This prevents the user from selecting a custom region, and forces
them to select a full output.
> Add -r flag to slurp

- .builds/alpine.yml
- .builds/archlinux.yml
- .builds/freebsd.yml
- contrib/config.sample
- meson.build
- src/core/config.c
- src/core/main.c
- xdg-desktop-portal-wlr.5.scd
Resolves: #96 
Note: inih doesn't escape quotes around a value, so this will break some configs.
#118 has made parsing much simpler.
> Use inih instead of libiniparser

- contrib/systemd/xdg-desktop-portal-wlr.service.in
This makes it clear xdpw requires WAYLAND_DISPLAY to be set before
being started.
Inspired by the mako service [1].
[1]: https://github.com/emersion/mako/blob/master/contrib/systemd/mako.service
> contrib/systemd: add ConditionEnvironment

- include/pipewire_screencast.h
- src/screencast/pipewire_screencast.c
- src/screencast/screencast.c
My idea how to fix #134. Probably needs review, and is only compile-tested atm.
> screencast: improve cleanup on error in xdpw_screencast_init()

- .builds/freebsd.yml
Follow up #126. inih exposes required CFLAGS/LDFLAGS via pkg-config, so hooking `/usr/local` is no longer necessary.
> ci: drop FreeBSD workaround after 22af25749e29

- src/core/config.c
Fixes: https://github.com/emersion/xdg-desktop-portal-wlr/issues/149
> config: handle missing HOME env variable gracefully

- include/screencast_common.h
- src/screencast/pipewire_screencast.c
- src/screencast/screencast.c
- src/screencast/wlr_screencast.c
Read the negotiated maxFramerate from pipewire and use that for our timer to prevent unnecessary screencopies. 
I don't know any usefull client, which announces maxFramerate yet, but hardcoding them in obs-studio worked.
> screencast: use negotiated maxFramerate from pipewire

- src/core/main.c
This makes xdpw exit when either the D-Bus daemon, the Wayland
compositor or Pipewire is shut down. This avoids having dangling
non-functional xdpw instances, e.g. when restarting the compositor.
To test, start Sway nested in Sway, run xdpw with
WAYLAND_DISPLAY=wayland-2, and exit the nested Sway.
> Handle POLLHUP

- src/screencast/screencast.c
- src/screenshot/screenshot.c
As per `man sd_bus_message_read`, boolean items should be read into an int rather than a bool as the latter can cause memory corruption.
(I'm not sure if this currently causes any issues in xdpw, but I did encounter this bug in a portal I'm writing that's based on xdpw.)
> Fix potential memory corruption when reading bools

- include/screencast_common.h
- src/screencast/pipewire_screencast.c
- src/screencast/screencast_common.c
- src/screencast/wlr_screencast.c
Updated and rebased and probably rewritten large parts of this MR to work with #141. So there are some old and probably some wrong things in the discussions.
-----------------------------------------------------------------------------------------------------------
I looked into buffertype handling in pipewire and talked to @wtay at #pipewire about it.
This draft is to show the current state (of at least my understanding).
-  SPA_PARAM_BUFFERS_dataType
SPA_PARAM_BUFFERS_dataType should be set by a consumer not by a producer as a bitmap to indicate the supported buffer types.
- {add,remove}_buffer callbacks
those callbacks are called, if pipewire adds or removes a new pw_buffer. 
If no alloc flag is used to connect to pipewire the pw_buffer is read-only and buffer->datas[].type contains …
> Improve pipewire buffertype handling

- src/screencast/pipewire_screencast.c
- src/screencast/screencast.c
> screencast: fix pipewire default id_node

- include/pipewire_screencast.h
- include/screencast_common.h
- include/wlr_screencast.h
- meson.build
- src/screencast/pipewire_screencast.c
- src/screencast/screencast.c
- src/screencast/screencast_common.c
- src/screencast/wlr_screencast.c
This MR aims to implement screencast driven by pipewire as explained in #137.
Resolves: #137 
~~Depends: #150~~
~~Depends: #148~~
~~Depends: #46~~
~~Depends: #61~~
> use pipewire buffers

- meson.build
- src/screencast/screencast_common.c
This makes PipeWire 0.3.41 the minimum required version, as the colour formats were introduced in that version.
> Add support for 10-bit colour formats

- src/screencast/screencast_common.c
This was missed in the original PR adding support for 10-bit colour.
> Implement xdpw_format_pw_strip_alpha for 10-bit colour

- src/screencast/screencast.c
According to the documentation [1] pw_loop_iterate (a macro for
spa_loop_control_iterate) will return the number of dispatched fd's
which don't have any value for error handling.
[1] https://docs.pipewire.org/group__spa__loop.html#ga3bae0b32100f5752b3372a505c8e04f6
> screencast: remove check on loop_iterate

- meson.build
PipeWire 0.3.49 added locale aware string functions to the spa library,
which are only available defining _GNU_SOURCE [1]. This will be fixed in
the next PipeWire release [2]
[1] https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/5f4d031db0a5515936b4d1943110e7cc87c30059
[2] https://gitlab.freedesktop.org/pipewire/pipewire/-/merge_requests/1206/
> build: define _GNU_SOURCE for PipeWire 0.3.49

- include/pipewire_screencast.h
- include/screencast_common.h
- src/core/session.c
- src/screencast/pipewire_screencast.c
- src/screencast/screencast.c
- src/screencast/screencast_common.c
- src/screencast/wlr_screencast.c
Using the on_process event of the PipeWire can create a race condition
when a previous started screencast hasn't finished before the next
event.
This MR is composed of following parts:
* nuke the racy on_process part
* cleanup some stuff
* intruduce xdpw_buffers 
* decouple the actual buffer (xdpw_buffer) from the pw_buffer carrier and swap the buffer from the PipeWire queue after each copy.
* Relax the swap incase the PipeWire queue is lagging behind.
Resolves: #182
> screencast: unmess the pipewire/wlr split

- .builds/alpine.yml
- .builds/archlinux.yml
- .builds/freebsd.yml
- include/config.h
- include/screencast_common.h
- include/wlr_screencast.h
- meson.build
- protocols/linux-dmabuf-unstable-v1.xml
- protocols/meson.build
- src/core/config.c
- src/screencast/pipewire_screencast.c
- src/screencast/screencast.c
- src/screencast/screencast_common.c
- src/screencast/wlr_screencast.c
- xdg-desktop-portal-wlr.5.scd
Splits the part containing the modifierless codepaths for dmabuf screensharing from #152 
Depends: #141 
Depends: #184
> Dmabuf modifierless

- wlr.portal
The compositor is phoc but XDG_CURRENT_DESKTOP has "Phosh".
> Add phosh to portal's UseIn list

- src/screencast/pipewire_screencast.c
Calling gbm_bo_create_with_modifiers2(...) and setting the modifiers
pointer to NULL for the same result as gmb_bo_create(...) is a MESA hack,
which I missed to remove from 84282e9b5f086014bd5f0ce36668e1265cc58af0.
> screencast: Remove MESA hack from the old gbm api fallback

- include/screencast_common.h
- include/wlr_screencast.h
- src/screencast/wlr_screencast.c
Since version 4 wl_output announces a name for the output. This removes
the need to retrieve this information from the xdg-output protocol.
> screencast: remove xdg-output protocol

- src/screencast/pipewire_screencast.c
- src/screencast/screencast_common.c
When having to share buffers between modifier aware APIs and modifier unaware APIs the common denominator is to create a buffer with linear layout. This MR announces support for a linear modifier when the compositor only supports implicit modifiers using the `GBM_BO_USE_LINEAR` flag to create a buffer with linear layout.
> Improve Interoperability between APIs using explicit and implicit modifiers

- contrib/wlroots-portals.conf
This is an example configuration for choosing the portal implementations which should be used [1]. Compositors and distributions are expected to ship their modified version according to their choice of components.
[1] https://github.com/flatpak/xdg-desktop-portal/pull/955
Resolves: #268
> contrib: Add portals config example

- meson.build
[NetBSD >= 10.0](https://github.com/netbsd/src/commit/75f1bc6655cf) and [FreeBSD >= 14.0](https://github.com/freebsd/freebsd-src/commit/af93fea71038) have native `timerfd` support. `git log -p` doesn't show any `signalfd` references.
See also [build log](https://github.com/emersion/xdg-desktop-portal-wlr/files/12447597/xdg-desktop-portal-wlr-0.7.0.3.log).
> build: drop unused signalfd dependency

- src/core/main.c
sd-bus requires that `sd_bus_get_fd`, `sd_bus_get_events`, and `sd_bus_get_timeout` are called for every invocation of `poll`, and the returned FD, events, and timeout used.  In particular, sd-bus may return `events=0` and `timeout=0` if it already has dbus messages to process in its receive queue.
xdpw currently doesn't call `sd_bus_get_events` or `sd_bus_get_timeout` at all.  This can result in the situation where xdpw goes into a `poll` with no timeout and a message in sd-bus' receive queue is never handled until another dbus message arrives.  I have a case where this ignored messages causes xdg-desktop-portal to hang.
This commit changes the polling code to match sd-bus' requirements.
Fixes #281
> Fix bug in sd-bus polling

- include/screencast_common.h
- include/wlr_screencast.h
- src/screencast/screencast.c
- src/screencast/wlr_screencast.c
This PR fixes 2 errors in the response returned by the screencast interface:
- The source type was wrong (`1 << MONITOR` -> `MONITOR`).
- The position was hardcoded as (0, 0). If the compositor supports the xdg-output protocol, use that protocol to get the correct position and report it. Otherwise, omit the position entirely.
> Screencast response fixes

- meson.build
Instead of relying on sh to setup stdin/stdout, we can just ask Meson to do that.
> build: simplify scdoc invocation

- src/screencast/screencast_common.c
All formats except ARGB8888 and XRGB8888 are guaranteed to always match the DRM FourCC.
> screencast: simplify wl_drm format code conversions

- meson.build
Makes it easier to tell if something has been auto-disabled due to
a missing dependency.
> build: add summary for auto-detected features

- meson.build
If somehow the compiler doesn't support -D, we should fail hard instead of omitting the define. Should also speed up Meson setup time a bit.
> build: don't use cc.get_supported_arguments() for -D flag

- src/screenshot/screenshot.c
On scaled outputs grim returns scaled images.
This breaks the enforced invariant in exec_color_picker() to expect single pixel images.
Force grim to use a scale of "1" to avoid this.
> colorchooser: force grim to only return a single pixel

- src/screenshot/screenshot.c
The xdpw request creates an object on the bus.
Not removing it means that the next call to method_pick_color() will
fail as the old object is still around.
Also make sure to clean up in error cases.
>  colorchooser: clean up xdpw request

- src/screencast/screencast.c
In the same vein as aff78aeecd324034c6e7e976f0156c04e83f6459, `WINDOW` is the value and not the index in the bitmask. But additionally, as I understand it, a "non-monitor" source type would be one that lacks `MONITOR` rather than one that includes `WINDOW` (or `VIRTUAL`) at all.
Technically this is a change in behavior since previously `WINDOW`-only source types were accepted but treated as `MONITOR` source types, and those will now be rejected (as only `VIRTUAL` source types were technically checked by mistake due to the bitmask value/index checking bug).
> screencast: fix SelectSources type bitmask check

- src/screencast/pipewire_screencast.c
Fixes undefined behavior detected by UBsan:
runtime error: call to function xdpw_wlr_frame_capture through pointer to incorrect function type 'void (*)(void *)'
> pipewire: use a wrapper function for timer callback

- include/screencast_common.h
- src/screencast/screencast_common.c
- src/screencast/wlr_screencopy.c
The new xdpw buffer constraint system did not account for wlr_screencopy sending the same constraints on every single frame.
In wlr_screencopy, check if a buffer matches the current constraints and only complain if it does not. This is the original behavior, albeit checking the allocated buffer details rather than focusing on the configured pipewire details.
(This is unfortunately not portable to ext_image_copy without sorting out dmabuf device comparison.)
Fixes: https://github.com/emersion/xdg-desktop-portal-wlr/pull/326#issuecomment-2948355389
> Fix wlr_screencopy regression

- src/screencast/ext_image_copy.c
- src/screencast/fps_limit.c
- src/screencast/pipewire_screencast.c
- src/screencast/wlr_screencast.c
- src/screencast/wlr_screencopy.c
The fps limit logic was throttling the time between the completion of one recorded frame and the request for the next frame. This means that the time it takes to request the frame, including if the compositor stalls for a frame to be available, is not measured as part of the current frame rate.
Measure from start of frame till start of frame.
(I didn't run into a particular issue here including in test, just seemed wrong.)
> Throttle fps from start of frame capture
